### ISSUE TITLE
No Apks on the Releases page

### ISSUE THREAD

**Issue by paju1986** [paveloom-f/lbry-android#3]
There is no apks available for download

**Comment by nukelr** [comment]
Indeed...

**Comment by paveloom** [comment]
Oh, it seems like I wasn't getting notifications from this repository. Sorry for the delay.

I suppose there was an automatic build that somehow bypassed the latest release check and tried to recreate the release. Since the code base of the original repository is full of deprecated methods, the build failed, but a release was created anyway, without an artifact.

I'm looking for a solution on the [`test-build`](https://github.com/paveloom-f/lbry-android/pull/4) branch, but I am quite busy at the moment, so this will have to wait for a couple of days.

**Comment by nukelr** [comment]
I should thank you instead :-) ...this motivated me to try building the app myself and I succeeded! I would ask if you know how to disable the autoupdate feature of lbry-desktop in the code. Any suggestion would be very appreciated and thank you so much for the good job you did!! 
Anyway I've used your patches on the lbry-fdroid sources to get rid of Goolag Firebase s**t too ;) You could consider to do that too for your releases ;)

**Comment by paveloom** [comment]
Aight, downgrading NDK to `r16b` was enough. The APKs are back on the [Releases](https://github.com/paveloom-f/lbry-android/releases) page.

@nukelr, concerning the auto-update feature of `lbry-desktop`, I just looked at the code, and I think you should find where this `doCheckUpgradeSubscribe` method is used and disable it.

![doCheckUpgradeSubscribe](https://user-images.githubusercontent.com/49961859/153770636-0399eda8-1b2b-4455-8f9c-8708054e0ebc.png)

Concerning the F-Droid version, I didn't even know about that repository. Will look into it.

**Comment by nukelr** [comment]
Thanks I will look for that. 
Anyway regarding lbry-fdroid if you look into the gradle.build you will see that the 64bit variant is disabled ...I tried with uncommenting the lines and I got a working 64bit release. I don't know why they did that.

**Comment by paveloom** [comment]
Yep, see the [change](https://github.com/lbryio/lbry-fdroid/commit/88c2c11a017f3dd3c191437248d51b81c6a6e871) and the [reasoning](https://github.com/lbryio/lbry-fdroid/issues/3#issuecomment-701261469).
